### ISSUE TITLE
Allow logging in to any homeserver

### ISSUE THREAD

**Issue by jansol** [neilalexander/seaglass#1]
Currently matrix.org is hardcoded. Consider using something like mujx/nheko#35 instead.

**Comment by neilalexander** [comment]
You can change the homeserver by clicking the cog icon on the login page. I plan eventually to add support for well-known discovery or similar.

**Comment by jansol** [comment]
Right, I somehow managed to miss that. For the time being though, a naïve attempt at poking /versions based on the domain part of the mxid would already massively improve the experience. And showing the config popup automatically if the probe fails.

**Comment by jansol** [comment]
That is, however, a separate issue.
