### ISSUE TITLE
deleting aliases occurs instantly, not when you hit save

### ISSUE THREAD

**Issue by ara4n** [neilalexander/seaglass#11]
it's surprising UX that you have a 'save' button on the aliases setting screen, but it looks like in practice the aliases are deleted (and added) immediately as you interact with the page; not when you hit save

**Comment by neilalexander** [comment]
I don't seem to be able to reproduce this. I can freely make changes to any of the aliases, adding, deleting and making/removing primary, and then see if anything has changed from Riot, and nothing happens until the "Save" button is clicked on the Aliases sheet.

I've added a little bit of extra wiring to make sure that the correct button is validated on each `IBAction`, and to also add some stdout output for each button press on that sheet. Can you retest?

**Comment by ara4n** [comment]
hm; is it possible the changes were applied even if you hit Cancel rather than Save? As I hit Cancel and they were definitely applied - i assumed they had already been applied but might have happened at that point. can’t test today i’m afraid; am on hol

**Comment by neilalexander** [comment]
If that was happening, the additional check in the `IBAction` for the right button seems to have solved it. I can't reproduce so will close for now, until it crops up again. ;-)
