### ISSUE TITLE
Add some kind of auto update mechanism

### ISSUE THREAD

**Issue by aaronraimist** [neilalexander/seaglass#19]
Maybe [Sparkle?](https://sparkle-project.org)

**Comment by aaronraimist** [comment]
I'm going to start working on implementing Sparkle. I probably won't have anything ready until the ~26th since I'll be pretty busy with college starting back up. If anyone else is going to implement it faster than that just ping me.

**Comment by neilalexander** [comment]
Will assign this to you if you are happy to look into it!
