### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by diogovieira** [neilalexander/seaglass#2]
Hello!

Congratulations on the client, seems cool. Would it be possible to add releases for easy testing for those avoiding having to build it?

**Comment by neilalexander** [comment]
Hi, thanks!

I'll be looking to implement CI builds soon, probably with CircleCI, which will be able to provide binary builds.

**Comment by aaronraimist** [comment]
@neilalexander you saw that [CircleCI costs $39/month for Mac builds right](https://circleci.com/pricing/#build-os-x)? I was just going to set this up and they didn't even warn me that it was going to cost money until I had already written out the `config.yml` file 🤦‍♂️.

**Comment by neilalexander** [comment]
Yikes - I guess macOS isn't covered by their open-source-projects-for-free policy!

**Comment by aaronraimist** [comment]
This can be closed. @diogovieira unsigned builds are now available. All you need to do is right click to open the first time.

**Comment by diogovieira** [comment]
Great! Thank you very much @aaronraimist 👍
