### ISSUE TITLE
Closing the main window and then reopening causes all rooms to be duplicated in the list

### ISSUE THREAD

**Issue by aaronraimist** [neilalexander/seaglass#24]
![screen shot 2018-08-14 at 3 42 01 pm](https://user-images.githubusercontent.com/5855073/44117334-a546a0e8-9fd8-11e8-8187-b85da4a61b8f.png)

**Comment by neilalexander** [comment]
The `NSArrayController` responsible for the room cache is probably not being cleared when the window is closed/reopened, should be a simple fix.

**Comment by neilalexander** [comment]
Please retest!
