### ISSUE TITLE
Room events showing more than once

### ISSUE THREAD

**Issue by yangm97** [neilalexander/seaglass#28]
<img width="186" alt="screen shot 2018-08-17 at 00 20 45" src="https://user-images.githubusercontent.com/4412002/44246219-63c6f000-a1b3-11e8-9fdd-53e62b93f47d.png">

Noticed it happening on:

- join events
- leave events

**Comment by neilalexander** [comment]
I am not sure if these events are always duplicate or if sometimes they are miscategorised - I think sometimes these events appear too when the user changes their avatar or display name, so need to look more closely at exactly what that behaviour is.

**Comment by yangm97** [comment]
<img width="950" alt="screen shot 2018-08-21 at 17 41 07" src="https://user-images.githubusercontent.com/4412002/44428009-7baec300-a569-11e8-8eef-2d23147e3b32.png">

Still happening on name changes.

**Comment by neilalexander** [comment]
Guess I still haven’t quite got the algorithm right! I’ll take a look over the next day or two.

**Comment by neilalexander** [comment]
Should be fixed as of 99dac388763833cf23a7c3141fe4b6df6b9cabae.
