### ISSUE TITLE
E2E user interface elements

### ISSUE THREAD

**Issue by neilalexander** [neilalexander/seaglass#34]
E2E rooms currently work in Seaglass but there is practically no user interface to control them. The following things are needed:

- [x] Allow user to share keys with other clients
- [x] Accept incoming keys from other clients and refresh encrypted messages (rather than needing to restart Seaglass, as you do today)
- [x] Show verified and unverified devices 
- [x] Allow a user to enable encryption on a room
- [x] Show button to re-request keys on a message that failed to decrypt
- [x] Encryption settings in User Settings, including device key for verification

**Comment by aaronraimist** [comment]
Also you need to add the users Seaglass device key to the UI somewhere so it can be verified in other devices.

**Comment by neilalexander** [comment]
Yes - that will indeed be in the User Settings window, which I started working on today. I'll add it to the list.

**Comment by neilalexander** [comment]
Device key is accessible through Preferences now.
<img width="562" alt="screen shot 2018-09-18 at 23 05 22" src="https://user-images.githubusercontent.com/310854/45722385-f89e7e00-bba3-11e8-9ed5-0c59a957eb47.png">

**Comment by neilalexander** [comment]
Commit cfa21e0 allows re-requesting encryption keys, which just about means this is closed off now.
<img width="950" alt="screen shot 2018-09-19 at 13 03 36" src="https://user-images.githubusercontent.com/310854/45752157-7ac28d00-bc0c-11e8-836d-a3b1f59b47f5.png">
