### ISSUE TITLE
README missing info on pod

### ISSUE THREAD

**Issue by shtrom** [neilalexander/seaglass#42]
`pod` doesn't seem to ship with OS X by default. It would be good for the README to indicate how to install it:

       brew install cocoapods

**Comment by aaronraimist** [comment]
If you're going to add that then you should probably add a link to brew.sh as well.

**Comment by neilalexander** [comment]
Can CocoaPods not be installed using the RubyGems package manager built into macOS?
```
sudo gem install cocoapods
```
If so then this might be a bit friendlier than `brew`.

**Comment by shtrom** [comment]
On Sun 26 Aug 2018 at 05:10:39 -0700, Neil Alexander wrote:
> Can CocoaPods not be installed using the RubyGems package manager built into macOS?
> ```
> sudo gem install cocoapods
> ```
> If so then this might be a bit friendlier than `brew`.

Haven't tried, but I agree reducing the dependencies of dependencies
would be better.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.
