### ISSUE TITLE
Support Lower MacOS Versions (10.12)

### ISSUE THREAD

**Issue by anoadragon453** [neilalexander/seaglass#68]
Seaglass will run on MacOS Sierra, however the chat view and room avatars are not showing.

![No messages](https://i.imgur.com/rxlCons.png)

This is apparently due to a 10.13+ only feature used to oriented the messages. If it were possible to do so without that feature then more users such as myself could use Seaglass :D

**Comment by neilalexander** [comment]
Duplicate of #49.
