### ISSUE TITLE
Improve resizing performance

### ISSUE THREAD

**Issue by aaronraimist** [neilalexander/seaglass#71]
- [ ] Improve performance of [`toAttributedStringFromMarkdown(justify: NSTextAlignment) -> NSAttributedString`](https://github.com/neilalexander/seaglass/blob/860050cd6523cc5dc149313c1845ce105595822a/Seaglass/Extension/String.swift#L23) or call it less often

TSMarkdownParser seems slow. Is it possible to not have this called on every redraw?

----

- [ ] Cache NSImages created for users without a profile picture

https://github.com/neilalexander/seaglass/blob/d991fe80846d36712a5ec01faba4d15b89115721/Seaglass/Subclass/Image%20Views/AvatarImageView.swift#L103

... or speed up [`create(withLetterString: String = "?") -> NSImage`](https://github.com/neilalexander/seaglass/blob/396a4bf554af37591ffcb10acb1adeba6c3cd807/Seaglass/Extension/NSImage.swift#L36)

If you just `return startImage` immediately in that method, resizing speeds up significantly (at least when only changing width) so that method seems to be slowing down resizing a lot.

----

![screen shot 2018-09-13 at 12 19 02 am](https://user-images.githubusercontent.com/5855073/45468524-a9130a80-b6ea-11e8-85da-53a06d8e0e81.png)

**Comment by aaronraimist** [comment]
Wish GitHub gave regular people the ability to set milestones and tags but this is probably a least a post v0.1 thing.

**Comment by neilalexander** [comment]
I'll put this on v0.2 milestone for now as it's more of an optimisation thing rather than a get-it-to-work thing.

**Comment by neilalexander** [comment]
`NSImage` for avatars etc are now cached in memory so there may be some improvement there. I've also guarded against unnecessary table redraws when the drawn event hasn't changed in any way, so I'd be interested to understand if this improves things for you. At a first glance, resize performance has improved dramatically here.

**Comment by aaronraimist** [comment]
Yes I am quite happy with the performance in d3a661c, feel free to close this unless there is further stuff you want to track.

**Comment by neilalexander** [comment]
Good stuff - let’s reopen if we face any more performance issues in the future.
