### ISSUE TITLE
Server selector button is disabled after you have logged in once

### ISSUE THREAD

**Issue by aaronraimist** [neilalexander/seaglass#75]
## Specifications

  - Seaglass Version: 0.0.445-6bef0d2
  - macOS Version: 10.13.6

## Expected Behavior

Should be able to change server so you can login to a different account on a different server

## Actual Behavior

Server selector "gear" icon is disabled.

**Comment by neilalexander** [comment]
Is this happening during automatic login, or after clicking "Cancel"?

**Comment by aaronraimist** [comment]
After clicking cancel
