### ISSUE TITLE
Crash when viewing #rust-finland:matrix.org

### ISSUE THREAD

**Issue by jansol** [neilalexander/seaglass#87]
## Specifications

  - Seaglass Version: 26d2109b
  - macOS Version: 10.14

## Expected Behavior
Business as usual

## Actual Behavior
Fatal error: Unexpectedly found nil while unwrapping an Optional value in RoomMessageInline.swift:108

## Steps to Reproduce the Problem

1. Join room (possibly with another client)
2. View room in Seaglass

**Comment by aaronraimist** [comment]
Looks like this was fixed by #90. Feel free to reopen if you are still experiencing this on the latest release.
