### ISSUE TITLE
Change auto-login text

### ISSUE THREAD

**Issue by anoadragon453** [neilalexander/seaglass#88]
"Login automatically when next started" -> "Login automatically".

Shorter and cleaner, and people know what you mean.

**Comment by aaronraimist** [comment]
If you want to fix this yourself, changing this should be really easy.

https://github.com/neilalexander/seaglass/blob/26d2109b27e916cf1a3416bff924cda65d7bd93e/Seaglass/Base.lproj/Main.storyboard#L3878

**Comment by anoadragon453** [comment]
I know, but not at my computer atm so was lazy :P
